ci(docker_check): fix linting

diff --git a/.github/workflows/base_image_validity.yaml b/.github/workflows/base_image_validity.yaml
--- a/.github/workflows/base_image_validity.yaml
+++ b/.github/workflows/base_image_validity.yaml
@@ -11,34 +11,33 @@ jobs:
     steps:
       - name: get config file from .devcontainer
         uses: actions/checkout@v3
-
       - name: List contents of .devcontainer directory
         run: |
           ls -la .devcontainer
-    - name: Set environment variables
+      - name: Set environment variables
+          run: |
+            export DEFAULT_PYTHON_VERSION=$(awk -F "=" '/default_python_version/ {print $2}' .devcontainer/config.ini)
+            export CUDA=$(awk -F "=" '/default_cuda/ {print $2}' .devcontainer/config.ini)
+            export CUDNN=$(awk -F "=" '/default_cudnn/ {print $2}' .devcontainer/config.ini)
+            export GPU_AVAILABLE=$(awk -F "=" '/default_gpu_available/ {print $2}' .devcontainer/config.ini)
+            export UBUNTU_VERSION=$(awk -F "=" '/default_ubuntu_version/ {print $2}' .devcontainer/config.ini)
+      - name: Check Docker Image
         run: |
-          export DEFAULT_PYTHON_VERSION=$(awk -F "=" '/default_python_version/ {print $2}' .devcontainer/config.ini)
-          export CUDA=$(awk -F "=" '/default_cuda/ {print $2}' .devcontainer/config.ini)
-          export CUDNN=$(awk -F "=" '/default_cudnn/ {print $2}' .devcontainer/config.ini)
-          export GPU_AVAILABLE=$(awk -F "=" '/default_gpu_available/ {print $2}' .devcontainer/config.ini)
-          export UBUNTU_VERSION=$(awk -F "=" '/default_ubuntu_version/ {print $2}' .devcontainer/config.ini)
-    - name: Check Docker Image
-      run: |
-        if docker inspect nvidia/cuda:${{ env.CUDA }}-${{ env.CUDNN }}-devel-ubuntu${{ env.UBUNTU_VERSION }} &> /dev/null; then
-          echo "Docker image exists"
-        else
-          echo "Docker image does not exist"
-          exit 1 # add this line to make the step fail
-        fi
-    - name: Notify User
-      if: failure()
-      uses: actions/github-script@v3
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          github.issues.create({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            title: 'Docker image does not exist',
-            body: 'The Docker image <image-name>:<image-tag> does not exist. Please check the build process and try again.'
-          })
+          if docker inspect nvidia/cuda:${{ env.CUDA }}-${{ env.CUDNN }}-devel-ubuntu${{ env.UBUNTU_VERSION }} &> /dev/null; then
+            echo "Docker image exists"
+          else
+            echo "Docker image does not exist"
+            exit 1 # add this line to make the step fail
+          fi
+      - name: Notify User
+        if: failure()
+        uses: actions/github-script@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            github.issues.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: 'Docker image does not exist',
+              body: 'The Docker image <image-name>:<image-tag> does not exist. Please check the build process and try again.'
+            })
