ci(styling): fix

diff --git a/.github/workflows/base_image_validity.yaml b/.github/workflows/base_image_validity.yaml
--- a/.github/workflows/base_image_validity.yaml
+++ b/.github/workflows/base_image_validity.yaml
@@ -19,23 +19,23 @@ jobs:
         run: |
           python -m pip install configparser
           python -c "from configparser import ConfigParser; config = ConfigParser(); config.read('.devcontainer/config.ini'); print(f'default_python_version={config.get('DEFAULT', 'default_python_version')}'); print(f'CUDA={config.get('DEFAULT', 'default_cuda')}'); print(f'CUDNN={config.get('DEFAULT', 'default_cudnn')}'); print(f'UBUNTU_VERSION={config.get('DEFAULT', 'default_ubuntu_version')}')"
-        - name: Check Docker Image
-          run: |
-            if docker inspect nvidia/cuda:${{ env.CUDA }}-${{ env.CUDNN }}-devel-ubuntu${{ env.UBUNTU_VERSION }} &> /dev/null; then
-              echo "Docker image exists"
-            else
-              echo "Docker image does not exist"
-              exit 1 # add this line to make the step fail
-            fi
-        - name: Notify User
-          if: failure()
-          uses: actions/github-script@v3
-          with:
-            github-token: ${{ secrets.GITHUB_TOKEN }}
-            script: |
-              github.issues.create({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                title: 'Docker image does not exist',
-                body: 'The Docker image <image-name>:<image-tag> does not exist. Please check the build process and try again.'
-              })
+      - name: Check Docker Image
+        run: |
+          if docker inspect nvidia/cuda:${{ env.CUDA }}-${{ env.CUDNN }}-devel-ubuntu${{ env.UBUNTU_VERSION }} &> /dev/null; then
+            echo "Docker image exists"
+          else
+            echo "Docker image does not exist"
+            exit 1 # add this line to make the step fail
+          fi
+      - name: Notify User
+        if: failure()
+        uses: actions/github-script@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            github.issues.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: 'Docker image does not exist',
+              body: 'The Docker image <image-name>:<image-tag> does not exist. Please check the build process and try again.'
+            })
